import { describe, expect, it } from "vitest";
import PERSONA_DOC from "../docs/persona.md?raw";
import {
  ANTI_PATTERNS,
  EXEMPLAR_MAX_WEIGHTED,
  LEGACY_COMMENTARY_EXEMPLARS,
  MOVE_EXAMPLES,
  OWNER_EXEMPLARS,
  PENDING_OWNER_EXEMPLARS,
  VOICE_CORE,
  stylePackFor,
} from "../src/rag/stylepack";
import { COMMENTARY_FACT_BUDGET, COMMENTARY_TAKE_BUDGET, COMMENTARY_TARGET } from "../src/rag/generate";
import { ARCHETYPES } from "../src/templates/archetypes";
import { attributionVerdict, checkRegister } from "../src/templates/validate";
import { POST_TEXT_LIMIT, fitsInPost, weightedLength } from "../src/templates/length";
import type { ArchetypeId } from "../src/templates/types";

const ALL_ARCHETYPES = Object.keys(ARCHETYPES) as ArchetypeId[];

describe("stylepack doctrine parity", () => {
  // VOICE_CORE quotes persona.md. If the doc changes, this fails and the
  // pack gets re-distilled — the doc stays the voice authority.
  const QUOTED = [
    "Claims need evidence. A filing is evidence. A vibe is not.",
    'Most "edges" are someone reading a public document first.',
    "Fact first, beat last, never blended.",
    "The reader finishes the sentence.",
    "Never impute knowledge or motive",
  ];
  for (const phrase of QUOTED) {
    it(`"${phrase.slice(0, 40)}..." is verbatim in BOTH persona.md and VOICE_CORE`, () => {
      expect(PERSONA_DOC).toContain(phrase);
      expect(VOICE_CORE).toContain(phrase);
    });
  }
});

describe("positive examples obey the doctrine they teach", () => {
  it("the example and anti-pattern banks cannot silently empty (loop-generated tests)", () => {
    // Every per-example test below is generated by a loop; an emptied array
    // generates zero tests and the suite stays green. These floors make an
    // emptying mutation loud.
    expect(MOVE_EXAMPLES.length).toBeGreaterThanOrEqual(4);
    expect(ANTI_PATTERNS.length).toBeGreaterThanOrEqual(8);
  });

  for (const ex of MOVE_EXAMPLES) {
    it(`passes the register guard: "${ex.text.slice(0, 40).replace(/\n/g, " ")}..."`, () => {
      // The pack's examples are the model's imitation targets. An example
      // that fails the register would teach the model to fail it too.
      expect(checkRegister(ex.text, ex.archetype)).toEqual([]);
      expect(fitsInPost(ex.text)).toBe(true);
    });
  }

  it("every example keeps the fact block first and any beat separated", () => {
    for (const ex of MOVE_EXAMPLES) {
      const parts = ex.text.split("\n\n");
      expect(parts.length).toBeLessThanOrEqual(2); // fact block + at most one beat
      // A REAL attribution, word-bounded — /per / alone is satisfied by
      // "Paper" or "Super".
      expect(parts[0]).toMatch(/\bper [A-Z]/);
    }
  });
});

describe("anti-patterns are genuinely negative", () => {
  it("declared registerRule entries actually trip checkRegister", () => {
    for (const p of ANTI_PATTERNS) {
      if (!p.registerRule) continue;
      const rules = checkRegister(p.example).map((i) => i.rule);
      expect(rules, `"${p.name}" claims to trip ${p.registerRule}`).toContain(p.registerRule);
    }
  });

  it("no anti-pattern example passes as a publishable post", () => {
    // Either the register guard catches it mechanically, or it embodies a
    // pattern the guard cannot see (motive, sourcing, framing) — in which
    // case it must NOT carry a REAL attribution, so it can never be mistaken
    // for a rendered post shape. "Real" is derived from the archetype table,
    // not a hand-kept list that drifts as attributions are added.
    // PR #53 makes attribution string-OR-map; normalize so this test survives
    // both shapes (mirrors checkRegister's own handling, not a reinvention).
    const attributions = Object.values(ARCHETYPES).flatMap((a): string[] => {
      const attr: unknown = a.attribution;
      return typeof attr === "string" ? [attr] : Object.values((attr as { map: Record<string, string> }).map);
    });
    for (const p of ANTI_PATTERNS) {
      const mechanical = checkRegister(p.example).length > 0;
      const postShaped = attributions.some((attr) => p.example.includes(attr));
      expect(mechanical || !postShaped, p.name).toBe(true);
    }
  });
});

describe("the margin rule (owner ruling 2026-08-06)", () => {
  // "Exemplars install at 272 weighted or under; generation targets 272;
  // hard cap 280 unchanged."
  it("generation targets the margin, and the hard cap is untouched", () => {
    expect(EXEMPLAR_MAX_WEIGHTED).toBe(272);
    expect(COMMENTARY_TARGET).toBe(EXEMPLAR_MAX_WEIGHTED);
    expect(POST_TEXT_LIMIT).toBe(280);
    // The two prompt budgets plus the blank line reach the TARGET, not the cap.
    expect(COMMENTARY_FACT_BUDGET + COMMENTARY_TAKE_BUDGET + 1).toBe(COMMENTARY_TARGET);
  });

  it("every v2 exemplar installed is inside the margin", () => {
    const v2 = OWNER_EXEMPLARS.filter((e) => e.v2);
    expect(v2.length).toBe(4);
    for (const e of v2) {
      expect(weightedLength(e.text), e.text.slice(0, 40)).toBeLessThanOrEqual(EXEMPLAR_MAX_WEIGHTED);
    }
  });

  it("the three v2 texts held back are held, not trimmed, and are still verbatim", () => {
    // "If any other installed exemplar sits above 272, report it, no silent
    // trims." [4] carries the owner's OWN replacement line and still lands at
    // 277: the swap moved it 280 -> 277, not under the margin.
    expect(PENDING_OWNER_EXEMPLARS.map((p) => p.n)).toEqual([2, 4, 5]);
    for (const p of PENDING_OWNER_EXEMPLARS) {
      expect(weightedLength(p.text), `[${p.n}]`).toBe(p.weighted);
      expect(p.weighted, `[${p.n}] would have installed`).toBeGreaterThan(EXEMPLAR_MAX_WEIGHTED);
      // None of them is in the live bank.
      expect(OWNER_EXEMPLARS.some((e) => e.text === p.text), `[${p.n}] leaked into the bank`).toBe(false);
    }
    expect(PENDING_OWNER_EXEMPLARS.find((p) => p.n === 4)!.text).toContain(
      "It'll still get called a red flag tonight by someone who didn't read past the dollar sign",
    );
  });

  it("the retired v1 seven are kept verbatim and never injected into a prompt", () => {
    expect(LEGACY_COMMENTARY_EXEMPLARS.length).toBe(4);
    for (const l of LEGACY_COMMENTARY_EXEMPLARS) {
      expect(weightedLength(l.text), l.text.slice(0, 30)).toBe(l.weighted);
      expect(OWNER_EXEMPLARS.some((e) => e.text === l.text)).toBe(false);
    }
    const everything = ALL_ARCHETYPES.map(stylePackFor).join("\n");
    for (const l of LEGACY_COMMENTARY_EXEMPLARS) {
      expect(everything).not.toContain(l.text.split("\n")[0]!);
    }
  });

  it("the only bank entries over the margin are the three whose v2 is blocked", () => {
    const over = OWNER_EXEMPLARS.filter((e) => weightedLength(e.text) > EXEMPLAR_MAX_WEIGHTED);
    // Their v1 originals stay live so no archetype loses its commentary
    // reference while the owner rules on the three rewrites.
    expect(over.length, over.map((e) => e.text.slice(0, 30)).join(" | ")).toBe(PENDING_OWNER_EXEMPLARS.length);
    expect(over.every((e) => e.register === "commentary")).toBe(true);
  });
});

describe("stylePackFor", () => {
  it("is deterministic", () => {
    expect(stylePackFor("CONGRESS_PTR")).toBe(stylePackFor("CONGRESS_PTR"));
  });

  it("assembles for every archetype and always carries core + moves + never-list", () => {
    for (const id of ALL_ARCHETYPES) {
      const pack = stylePackFor(id);
      expect(pack).toContain("STRUCTURAL LAW");
      expect(pack).toContain("THE THREE MOVES");
      expect(pack).toContain("NEVER DO");
    }
  });

  it("congress gets the measured section with its numbers; others do not", () => {
    const congress = stylePackFor("CONGRESS_PTR");
    expect(congress).toContain("CONGRESS PTR, MEASURED NOTES");
    // Body assertions, not heading-only: the measured figures themselves.
    for (const figure of ["174", "only 9", "52%", "40%"]) expect(congress).toContain(figure);
    for (const id of ALL_ARCHETYPES.filter((a) => a !== "CONGRESS_PTR")) {
      expect(stylePackFor(id), id).not.toContain("MEASURED NOTES");
    }
  });

  it("section BODIES survive in the assembled pack, not just headings", () => {
    const pack = stylePackFor("FILING_8K");
    // One load-bearing phrase per move, plus every anti-pattern's name and
    // reasoning — deleting a body while keeping its heading now fails.
    for (const phrase of [
      "zero connective tissue",
      "names the RECORD",
      "never shrinks commentary below its 200-280 contract",
    ]) {
      expect(pack).toContain(phrase);
    }
    for (const p of ANTI_PATTERNS) {
      expect(pack).toContain(p.name);
      expect(pack).toContain(p.why);
    }
  });

  it("never names the studied accounts — the prompt describes moves, not handles", () => {
    // Naming the accounts in the prompt would invite the model to imitate
    // them from training data, which is exactly the verbatim-echo risk the
    // pack exists to avoid. Handles live in docs/verification/, not here.
    const everything = ALL_ARCHETYPES.map(stylePackFor).join("\n");
    for (const handle of ["unusual_whales", "Heisenberg", "spectator_index", "stockmktnewz", "amit_is_investing"]) {
      expect(everything).not.toContain(handle);
    }
  });

  it("the owner exemplar bank is populated, congress-first, and every entry is register-clean", () => {
    expect(OWNER_EXEMPLARS.length).toBeGreaterThanOrEqual(20);
    // Congress-first: the signature archetype carries the deepest bank.
    const byArchetype = new Map<string, number>();
    for (const e of OWNER_EXEMPLARS) byArchetype.set(e.archetype, (byArchetype.get(e.archetype) ?? 0) + 1);
    const congressCount = byArchetype.get("CONGRESS_PTR") ?? 0;
    for (const [a, n] of byArchetype) {
      expect(congressCount, `${a} outnumbers CONGRESS_PTR`).toBeGreaterThanOrEqual(n);
    }
    for (const e of OWNER_EXEMPLARS) {
      const head = e.text.slice(0, 40).replace(/\n/g, " ");
      // Register rules that apply to ALL owner text: no em-dash, no hashtag,
      // no trailing question, no advice construction. (Archetype-less call:
      // the owner's exemplars abbreviate attributions deliberately. The
      // LENGTH rule is exempted for commentary — those exemplars run above
      // the cap BY DESIGN as voice references; output stays validator-capped.)
      const issues = checkRegister(e.text).filter((i) => e.register === "commentary" && i.rule === "length" ? false : true);
      expect(issues, head).toEqual([]);
      // The attribution rides the FIRST segment, always — but the RULE for
      // what counts is the validator's, not a regex copied next to it.
      // /\bper [A-Z]/ rejected two of the owner's own v2 exemplars: "per the
      // House Clerk" (lowercase article) and the FTC one, which carries its
      // citation in its subject and has no "per" phrase at all.
      //
      // `foreign` is counted as present, not as a failure: the owner's Form 4
      // exemplars say "per SEC" where the archetype pins "per SEC Form 4",
      // and that abbreviation is deliberate and pre-existing. Exactness is
      // enforced where it matters — on rendered output, with the payload.
      const v = attributionVerdict(e.text, e.archetype);
      // ONE named exception, and it is an OPEN OWNER DECISION, not a
      // tolerance: the RBI exemplar cites "per MPC statement", which names
      // no institution and is in no attribution table. src/ingesters/
      // rateAttribution.ts records the two ways out (build the rate source,
      // or re-file the exemplar); both are the owner's call. Listed here so
      // it stays visible instead of being waved through by a loose regex.
      if (!e.text.includes("per MPC statement")) {
        expect(v.trailing.length + v.embedded.length + v.foreign.length, `${head}: no attribution`).toBeGreaterThan(0);
      }
      if (e.register === "wire") {
        // Wire exemplars are postable as-is.
        expect(fitsInPost(e.text), head).toBe(true);
        expect(e.text.split(/\n\n+/).length, head).toBeLessThanOrEqual(2);
      } else {
        // Commentary exemplars are VOICE references: the owner writes them
        // above the platform cap on purpose; output stays validator-capped.
        expect(e.text.split(/\n\n+/).length, head).toBeLessThanOrEqual(3);
        expect(e.text.length, head).toBeLessThanOrEqual(360);
      }
    }
  });

  it("the stylepack itself never embeds exemplars (single home: buildPrompt)", () => {
    expect(stylePackFor("CONGRESS_PTR")).not.toContain("OWNER EXEMPLARS");
  });
});
