import { describe, expect, it } from "vitest";
import PERSONA_DOC from "../docs/persona.md?raw";
import {
  ANTI_PATTERNS,
  MOVE_EXAMPLES,
  OWNER_EXEMPLARS,
  VOICE_CORE,
  stylePackFor,
} from "../src/rag/stylepack";
import { ARCHETYPES } from "../src/templates/archetypes";
import { checkRegister } from "../src/templates/validate";
import { fitsInPost } from "../src/templates/length";
import type { ArchetypeId } from "../src/templates/types";

const ALL_ARCHETYPES = Object.keys(ARCHETYPES) as ArchetypeId[];

describe("stylepack doctrine parity", () => {
  // VOICE_CORE quotes persona.md. If the doc changes, this fails and the
  // pack gets re-distilled — the doc stays the voice authority.
  const QUOTED = [
    "Claims need evidence. A filing is evidence. A vibe is not.",
    'Most "edges" are someone reading a public document first.',
    "Fact first, beat last, never blended.",
    "The reader finishes the sentence.",
    "Never impute knowledge or motive",
  ];
  for (const phrase of QUOTED) {
    it(`"${phrase.slice(0, 40)}..." is verbatim in BOTH persona.md and VOICE_CORE`, () => {
      expect(PERSONA_DOC).toContain(phrase);
      expect(VOICE_CORE).toContain(phrase);
    });
  }
});

describe("positive examples obey the doctrine they teach", () => {
  it("the example and anti-pattern banks cannot silently empty (loop-generated tests)", () => {
    // Every per-example test below is generated by a loop; an emptied array
    // generates zero tests and the suite stays green. These floors make an
    // emptying mutation loud.
    expect(MOVE_EXAMPLES.length).toBeGreaterThanOrEqual(4);
    expect(ANTI_PATTERNS.length).toBeGreaterThanOrEqual(8);
  });

  for (const ex of MOVE_EXAMPLES) {
    it(`passes the register guard: "${ex.text.slice(0, 40).replace(/\n/g, " ")}..."`, () => {
      // The pack's examples are the model's imitation targets. An example
      // that fails the register would teach the model to fail it too.
      expect(checkRegister(ex.text, ex.archetype)).toEqual([]);
      expect(fitsInPost(ex.text)).toBe(true);
    });
  }

  it("every example keeps the fact block first and any beat separated", () => {
    for (const ex of MOVE_EXAMPLES) {
      const parts = ex.text.split("\n\n");
      expect(parts.length).toBeLessThanOrEqual(2); // fact block + at most one beat
      // A REAL attribution, word-bounded — /per / alone is satisfied by
      // "Paper" or "Super".
      expect(parts[0]).toMatch(/\bper [A-Z]/);
    }
  });
});

describe("anti-patterns are genuinely negative", () => {
  it("declared registerRule entries actually trip checkRegister", () => {
    for (const p of ANTI_PATTERNS) {
      if (!p.registerRule) continue;
      const rules = checkRegister(p.example).map((i) => i.rule);
      expect(rules, `"${p.name}" claims to trip ${p.registerRule}`).toContain(p.registerRule);
    }
  });

  it("no anti-pattern example passes as a publishable post", () => {
    // Either the register guard catches it mechanically, or it embodies a
    // pattern the guard cannot see (motive, sourcing, framing) — in which
    // case it must NOT carry a REAL attribution, so it can never be mistaken
    // for a rendered post shape. "Real" is derived from the archetype table,
    // not a hand-kept list that drifts as attributions are added.
    // PR #53 makes attribution string-OR-map; normalize so this test survives
    // both shapes (mirrors checkRegister's own handling, not a reinvention).
    const attributions = Object.values(ARCHETYPES).flatMap((a): string[] => {
      const attr: unknown = a.attribution;
      return typeof attr === "string" ? [attr] : Object.values((attr as { map: Record<string, string> }).map);
    });
    for (const p of ANTI_PATTERNS) {
      const mechanical = checkRegister(p.example).length > 0;
      const postShaped = attributions.some((attr) => p.example.includes(attr));
      expect(mechanical || !postShaped, p.name).toBe(true);
    }
  });
});

describe("stylePackFor", () => {
  it("is deterministic", () => {
    expect(stylePackFor("CONGRESS_PTR")).toBe(stylePackFor("CONGRESS_PTR"));
  });

  it("assembles for every archetype and always carries core + moves + never-list", () => {
    for (const id of ALL_ARCHETYPES) {
      const pack = stylePackFor(id);
      expect(pack).toContain("STRUCTURAL LAW");
      expect(pack).toContain("THE THREE MOVES");
      expect(pack).toContain("NEVER DO");
    }
  });

  it("congress gets the measured section with its numbers; others do not", () => {
    const congress = stylePackFor("CONGRESS_PTR");
    expect(congress).toContain("CONGRESS PTR, MEASURED NOTES");
    // Body assertions, not heading-only: the measured figures themselves.
    for (const figure of ["174", "only 9", "52%", "40%"]) expect(congress).toContain(figure);
    for (const id of ALL_ARCHETYPES.filter((a) => a !== "CONGRESS_PTR")) {
      expect(stylePackFor(id), id).not.toContain("MEASURED NOTES");
    }
  });

  it("section BODIES survive in the assembled pack, not just headings", () => {
    const pack = stylePackFor("FILING_8K");
    // One load-bearing phrase per move, plus every anti-pattern's name and
    // reasoning — deleting a body while keeping its heading now fails.
    for (const phrase of [
      "zero connective tissue",
      "names the RECORD",
      "never shrinks commentary below its 200-280 contract",
    ]) {
      expect(pack).toContain(phrase);
    }
    for (const p of ANTI_PATTERNS) {
      expect(pack).toContain(p.name);
      expect(pack).toContain(p.why);
    }
  });

  it("never names the studied accounts — the prompt describes moves, not handles", () => {
    // Naming the accounts in the prompt would invite the model to imitate
    // them from training data, which is exactly the verbatim-echo risk the
    // pack exists to avoid. Handles live in docs/verification/, not here.
    const everything = ALL_ARCHETYPES.map(stylePackFor).join("\n");
    for (const handle of ["unusual_whales", "Heisenberg", "spectator_index", "stockmktnewz", "amit_is_investing"]) {
      expect(everything).not.toContain(handle);
    }
  });

  it("the owner exemplar bank is populated, congress-first, and every entry is register-clean", () => {
    expect(OWNER_EXEMPLARS.length).toBeGreaterThanOrEqual(20);
    // Congress-first: the signature archetype carries the deepest bank.
    const byArchetype = new Map<string, number>();
    for (const e of OWNER_EXEMPLARS) byArchetype.set(e.archetype, (byArchetype.get(e.archetype) ?? 0) + 1);
    const congressCount = byArchetype.get("CONGRESS_PTR") ?? 0;
    for (const [a, n] of byArchetype) {
      expect(congressCount, `${a} outnumbers CONGRESS_PTR`).toBeGreaterThanOrEqual(n);
    }
    for (const e of OWNER_EXEMPLARS) {
      const head = e.text.slice(0, 40).replace(/\n/g, " ");
      // Register rules that apply to ALL owner text: no em-dash, no hashtag,
      // no trailing question, no advice construction. (Archetype-less call:
      // the owner's exemplars abbreviate attributions deliberately. The
      // LENGTH rule is exempted for commentary — those exemplars run above
      // the cap BY DESIGN as voice references; output stays validator-capped.)
      const issues = checkRegister(e.text).filter((i) => e.register === "commentary" && i.rule === "length" ? false : true);
      expect(issues, head).toEqual([]);
      // The attribution rides the FIRST segment, always.
      expect(e.text.split(/\n\n+/)[0], head).toMatch(/\bper [A-Z]/);
      if (e.register === "wire") {
        // Wire exemplars are postable as-is.
        expect(fitsInPost(e.text), head).toBe(true);
        expect(e.text.split(/\n\n+/).length, head).toBeLessThanOrEqual(2);
      } else {
        // Commentary exemplars are VOICE references: the owner writes them
        // above the platform cap on purpose; output stays validator-capped.
        expect(e.text.split(/\n\n+/).length, head).toBeLessThanOrEqual(3);
        expect(e.text.length, head).toBeLessThanOrEqual(360);
      }
    }
  });

  it("the stylepack itself never embeds exemplars (single home: buildPrompt)", () => {
    expect(stylePackFor("CONGRESS_PTR")).not.toContain("OWNER EXEMPLARS");
  });
});
